apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-api-config
  namespace: simple-api
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"